apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-backend

  template:
    metadata:
      labels:
        app: flask-backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: flask-backend

          image: 540191526881.dkr.ecr.us-east-1.amazonaws.com/flask-backend

          ports:
            - containerPort: 5000

          env:
            - name: AWS_REGION
              value: "us-east-1"

            - name: DB_HOST
              value: "database-1.c2zmaks84ifc.us-east-1.rds.amazonaws.com"

            - name: SECRET_NAME
              value: "flask-backend-rds"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
